[2024-02-23T20:36:21.388+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-02-23T20:36:13.657794+00:00 [queued]>
[2024-02-23T20:36:21.398+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-02-23T20:36:13.657794+00:00 [queued]>
[2024-02-23T20:36:21.399+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-23T20:36:21.413+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): inaccurate> on 2024-02-23 20:36:13.657794+00:00
[2024-02-23T20:36:21.419+0000] {standard_task_runner.py:60} INFO - Started process 177 to run task
[2024-02-23T20:36:21.422+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2024-02-23T20:36:13.657794+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp5xl1gjax']
[2024-02-23T20:36:21.424+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask inaccurate
[2024-02-23T20:36:21.470+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate manual__2024-02-23T20:36:13.657794+00:00 [running]> on host cb189f2dc8f0
[2024-02-23T20:36:21.538+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-02-23T20:36:13.657794+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-23T20:36:13.657794+00:00'
[2024-02-23T20:36:21.547+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-23T20:36:21.548+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate' "]
[2024-02-23T20:36:21.571+0000] {subprocess.py:86} INFO - Output:
[2024-02-23T20:36:21.582+0000] {subprocess.py:93} INFO - inaccurate
[2024-02-23T20:36:21.583+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-23T20:36:21.604+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240223T203613, start_date=20240223T203621, end_date=20240223T203621
[2024-02-23T20:36:21.634+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-23T20:36:21.649+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
