[2024-03-02T22:46:23.930+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-03-02T22:46:23.940+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-03-02T22:46:23.941+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-02T22:46:23.955+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): inaccurate> on 2024-03-01 00:00:00+00:00
[2024-03-02T22:46:23.972+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp388xw3o_']
[2024-03-02T22:46:23.970+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-03-02T22:46:23.979+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask inaccurate
[2024-03-02T22:46:25.503+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2024-03-01T00:00:00+00:00 [running]> on host 6b5be2d0256f
[2024-03-02T22:46:25.684+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-03-02T22:46:25.700+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-02T22:46:25.703+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate' "]
[2024-03-02T22:46:25.748+0000] {subprocess.py:86} INFO - Output:
[2024-03-02T22:46:25.761+0000] {subprocess.py:93} INFO - inaccurate
[2024-03-02T22:46:25.763+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-02T22:46:25.793+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240301T000000, start_date=20240302T224623, end_date=20240302T224625
[2024-03-02T22:46:25.844+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-02T22:46:25.888+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
